-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6LaZrdzNBEn7Q6b0
D0DVI7YNoEjnVjq0/xWvSVHxboegCgYIKoZIzj0DAQehRANCAATeQXCm4WBs1fFB
xK7hk4lsHA5eU/EcBc1kUfVGUFf0JJrWp5sF4KaMaqmwTH3iSFdpmY8hYNoPaT+c
7cOlyLvs
-----END PRIVATE KEY-----